// Fixed C4 observation model. All iterative state below is native data.
#include <set>
#include <memory>
#include <unordered_map>
using X=std::array<double,3>;
using Mat=std::array<X,3>; // columns
X add(X a,X b){for(int j=0;j<3;++j)a[j]+=b[j];return a;}
X sub(X a,X b){for(int j=0;j<3;++j)a[j]-=b[j];return a;}
X mul(X a,double s){for(double&v:a)v*=s;return a;}
double dot(X a,X b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}
double norm(X a){return std::sqrt(dot(a,a));}
X unit(X a){double n=norm(a);if(n<1e-9)throw std::runtime_error("LOCAL_FRAME_DEGENERATE");return mul(a,1/n);}
X cross(X a,X b){return {a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]};}
X local(X p,Mat b){return {dot(p,b[0]),dot(p,b[1]),dot(p,b[2])};}
X expand(X p,Mat b){return add(add(mul(b[0],p[0]),mul(b[1],p[1])),mul(b[2],p[2]));}
Mat transported(Mat b,X t){t=unit(t);double c=std::clamp(dot(b[0],t),-1.,1.);if(c<-.999999)throw std::runtime_error("LOCAL_FRAME_DEGENERATE");X v=cross(b[0],t);Mat out;for(int j=0;j<3;++j)out[j]=add(add(b[j],cross(v,b[j])),mul(cross(v,cross(v,b[j])),1/(1+c)));return out;}
double quantile(std::vector<double> a,double q){if(a.empty())return std::numeric_limits<double>::quiet_NaN();std::sort(a.begin(),a.end());double p=q*(a.size()-1);size_t k=size_t(p);return a[k]+(a[std::min(k+1,a.size()-1)]-a[k])*(p-k);}
std::pair<X,X> principal(const std::vector<X>&points,X previous){if(points.size()<3)throw std::runtime_error("LOCAL_FRAME_DEGENERATE");X c={0,0,0};for(X p:points)c=add(c,p);c=mul(c,1./points.size());double a[3][3]={},v[3][3]={{1,0,0},{0,1,0},{0,0,1}};for(X p:points){p=sub(p,c);for(int i=0;i<3;++i)for(int j=0;j<3;++j)a[i][j]+=p[i]*p[j];}
 if(trace_context&&trace_context->enabled){std::vector<double> z={c[0],c[1],c[2]};for(auto&r:a)for(double x:r)z.push_back(x);event("pca_covariance",z);}
 for(int it=0;it<30;++it){int p=0,q=1;for(int i=0;i<3;++i)for(int j=i+1;j<3;++j)if(std::abs(a[i][j])>std::abs(a[p][q])){p=i;q=j;}if(std::abs(a[p][q])<1e-14)break;double angle=.5*std::atan2(2*a[p][q],a[q][q]-a[p][p]),cs=std::cos(angle),sn=std::sin(angle);event("pca_libm",{double(it),double(p),double(q),2*a[p][q],a[q][q]-a[p][p],angle,cs,sn});double pp=cs*cs*a[p][p]-2*sn*cs*a[p][q]+sn*sn*a[q][q],qq=sn*sn*a[p][p]+2*sn*cs*a[p][q]+cs*cs*a[q][q];for(int k=0;k<3;++k)if(k!=p&&k!=q){double ap=a[k][p],aq=a[k][q];a[k][p]=a[p][k]=cs*ap-sn*aq;a[k][q]=a[q][k]=sn*ap+cs*aq;}a[p][p]=pp;a[q][q]=qq;a[p][q]=a[q][p]=0;for(int k=0;k<3;++k){double vp=v[k][p],vq=v[k][q];v[k][p]=cs*vp-sn*vq;v[k][q]=sn*vp+cs*vq;}}
 int k=0;for(int j=1;j<3;++j)if(a[j][j]>a[k][k])k=j;if(a[k][k]<.0004)throw std::runtime_error("LOCAL_FRAME_DEGENERATE");X t={v[0][k],v[1][k],v[2][k]};if(dot(t,previous)<0)t=mul(t,-1);event("pca_result",{t[0],t[1],t[2],a[k][k]});return {unit(t),c};}
struct Cell {int x,y,z;bool operator==(const Cell&o)const{return x==o.x&&y==o.y&&z==o.z;}};
struct CellHash{size_t operator()(Cell k)const{return size_t(k.x)*73856093u^size_t(k.y)*19349663u^size_t(k.z)*83492791u;}};
Cell cell(X p){return {int(std::floor(p[0]/2)),int(std::floor(p[1]/2)),int(std::floor(p[2]/2))};}
struct Cloud {int frame;std::vector<X> world;std::unordered_map<Cell,std::vector<int>,CellHash> cells;};

struct FrameStore {
 std::map<int,std::shared_ptr<Cloud>> frames;std::mutex mutex;size_t builds=0;double build_seconds=0;
 void add_frame(int index,Arr xyz){auto a=xyz.unchecked<2>();if(a.shape(1)!=3)throw std::runtime_error("world Nx3 required");auto c=std::make_shared<Cloud>();c->frame=index;c->world.resize(a.shape(0));auto start=std::chrono::steady_clock::now();
  {py::gil_scoped_release release;for(py::ssize_t i=0;i<a.shape(0);++i)c->world[i]={a(i,0),a(i,1),a(i,2)};for(size_t i=0;i<c->world.size();++i)c->cells[cell(c->world[i])].push_back(int(i));std::lock_guard<std::mutex> lock(mutex);frames[index]=c;++builds;build_seconds+=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();while(!frames.empty()&&frames.begin()->first<index-11)frames.erase(frames.begin());}
 }
 std::map<int,std::shared_ptr<Cloud>> snapshot(const std::vector<int>&history){std::lock_guard<std::mutex> lock(mutex);std::map<int,std::shared_ptr<Cloud>> result;for(int k:history){auto it=frames.find(k);if(it==frames.end())throw std::runtime_error("snapshot frame expired/missing");result[k]=it->second;}return result;}
 py::dict stats(){std::lock_guard<std::mutex> lock(mutex);size_t n=0;for(auto&f:frames)n+=f.second->world.size();py::dict d;d["builds"]=builds;d["build_seconds"]=build_seconds;d["frames"]=frames.size();d["points"]=n;d["xyz_bytes"]=n*sizeof(X);return d;}
};

struct Obs{uint64_t key;X xyz,uvw;int age;double residual=0;};
struct Block{int step=0,state=2,original=2,rank=0;X anchor;V a={0,0};Mat B;X C;std::vector<Obs> points;double confidence=1,score=1,templ=1,prior=1,shape=0,margin=1,first=0,second=0;};
struct Path{Mat B;X C;std::vector<std::shared_ptr<Block>> blocks;double score=0,search=0;int pending=0;std::string reason="RANGE_LIMIT";};
struct FrameStep{X C;Mat B;Points old;double turn;V oa;bool firstok=false,firstweak=false;double first=0;std::string reason;std::vector<Obs> roi;std::vector<std::shared_ptr<Block>> accepted;};
std::vector<Obs> confirmed_current(const Path&p){std::vector<Obs> a;for(auto&b:p.blocks)if(b->state==2)for(auto&v:b->points)if(v.age==0)a.push_back(v);std::stable_sort(a.begin(),a.end(),[](auto&a,auto&b){return a.key<b.key;});return a;}
FrameStep next_frame(const Path&p){Timer frame_timer(profile_context,"PCA_frame_construction");auto obs=confirmed_current(p);if(trace_context&&trace_context->enabled){std::vector<uint64_t> ids;std::vector<double> v;for(auto&o:obs){ids.push_back(o.key);for(double x:o.xyz)v.push_back(x);}event("confirmed_current",v,ids);}if(obs.empty())throw std::runtime_error("NO_CURRENT_GEOMETRY");double end=-1e20;for(auto&o:obs)end=std::max(end,dot(sub(o.xyz,p.C),p.B[0]));std::vector<X> recent;for(auto&o:obs)if(dot(sub(o.xyz,p.C),p.B[0])>=end-8)recent.push_back(o.xyz);auto[t,c]=principal(recent,p.B[0]);FrameStep f;f.B=transported(p.B,t);f.C=add(c,mul(p.B[0],4-dot(sub(c,p.C),p.B[0])));f.turn=std::acos(std::clamp(dot(p.B[0],t),-1.,1.))*180/3.141592653589793;if(f.turn>5)throw std::runtime_error("ORIENTATION_JUMP");if(p.pending){f.C=add(p.C,mul(p.B[0],4));X d=local(sub(p.blocks.back()->anchor,f.C),f.B);f.C=add(f.C,expand({0,std::clamp(d[1],-.08,.08),std::clamp(d[2],-.08,.08)},f.B));}for(auto&o:obs){X q=local(sub(o.xyz,f.C),f.B);if(q[0]>=0&&q[0]<=8)f.old.push_back({q[1],q[2]});}return f;}
struct Overlap{bool ok,weak;double p90;};
Overlap overlap(const Points&p,const Points&t,V a){if(p.empty())return {false,true,std::numeric_limits<double>::quiet_NaN()};std::vector<double>d;double r=0;for(V x:p){double v=nn({x[0]-a[0],x[1]-a[1]},t).first;d.push_back(v);r+=std::min(v,.06)*std::min(v,.06);}double q=quantile(d,.9);return {q<=.03,q>.03&&q<=.05&&std::sqrt(r/d.size())<=.04,q};}
bool promote(Path&p,const Block&newblock){Timer promotion_timer(profile_context,"tentative_confirmation");std::vector<std::shared_ptr<Block>> confirmed,pending;for(auto&b:p.blocks)(b->state==2?confirmed:pending).push_back(b);if(pending.empty()||(newblock.state!=2&&pending.size()<2))return false;std::vector<X>a;size_t begin=confirmed.size()>3?confirmed.size()-3:0;for(size_t k=begin;k<confirmed.size();++k)a.push_back(confirmed[k]->anchor);for(auto&b:pending)a.push_back(b->anchor);if(a.size()<3)return false;std::vector<double>u;for(X x:a)u.push_back(dot(sub(x,a[0]),p.B[0]));if(*std::max_element(u.begin(),u.end())-*std::min_element(u.begin(),u.end())<2)return false;std::set<X>unique;for(auto&b:pending)for(auto&o:b->points)unique.insert(o.xyz);for(auto&o:newblock.points)unique.insert(o.xyz);if(unique.size()<3)return false;
 // Scale station before the tiny polynomial normal solve to limit conditioning.
 double scale=1;for(double x:u)scale=std::max(scale,std::abs(x));double M[3][6]={};for(size_t k=0;k<a.size();++k){double x=u[k]/scale,z[3]={1,x,x*x};for(int i=0;i<3;++i){for(int j=0;j<3;++j)M[i][j]+=z[i]*z[j];for(int j=0;j<3;++j)M[i][3+j]+=z[i]*a[k][j];}}
 for(int j=0;j<3;++j){int pivot=j;for(int i=j+1;i<3;++i)if(std::abs(M[i][j])>std::abs(M[pivot][j]))pivot=i;if(std::abs(M[pivot][j])<1e-13)return false;for(int k=0;k<6;++k)std::swap(M[j][k],M[pivot][k]);double v=M[j][j];for(int k=j;k<6;++k)M[j][k]/=v;for(int i=0;i<3;++i)if(i!=j){v=M[i][j];for(int k=j;k<6;++k)M[i][k]-=v*M[j][k];}}
 for(size_t k=0;k<a.size();++k){double x=u[k]/scale;X fitted;for(int j=0;j<3;++j)fitted[j]=M[0][3+j]+x*M[1][3+j]+x*x*M[2][3+j];if(norm(sub(fitted,a[k]))>.05)return false;}return true;}
struct Marcher{
 Trace trace_log;bool profiling=false;Counters profile;std::vector<std::vector<double>> step_profile;size_t broad_points=0,transformed_points=0;
 Solver solver;std::map<int,std::shared_ptr<Cloud>> clouds;bool tight_roi=false;Mat R,invR;X translation;int current=0;size_t updates=0,steps=0,roi_points=0;double native_seconds=0;
 Marcher(int threads,int iterations,int grid):solver(threads,iterations,grid){}
 void attach(FrameStore&store,const std::vector<int>&history){clouds=store.snapshot(history);}
 void options(bool exact_tight_roi){tight_roi=exact_tight_roi;}
 void diagnostics(bool trace,bool timers){trace_log.enabled=trace;profiling=timers;solver.trace=&trace_log;solver.profiling=timers;}
 py::list export_trace(){return trace_log.export_events();}
 void add_frame(int index,py::array_t<double,py::array::forcecast> xyz){Timer ingest_timer(profiling?&profile:nullptr,"history_ingest");auto a=xyz.unchecked<2>();if(a.shape(1)!=3)throw std::runtime_error("world Nx3 required");Cloud c;c.frame=index;c.world.resize(a.shape(0));for(py::ssize_t i=0;i<a.shape(0);++i)c.world[i]={a(i,0),a(i,1),a(i,2)};{py::gil_scoped_release release;Timer index_timer(profiling?&profile:nullptr,"index_build");for(size_t i=0;i<c.world.size();++i)c.cells[cell(c.world[i])].push_back(int(i));clouds[index]=std::make_shared<Cloud>(std::move(c));while(!clouds.empty()&&clouds.begin()->first<index-11)clouds.erase(clouds.begin());}}
 X sensor(X world){Timer transform_timer(profile_context,"map_current_transform");return local(sub(world,translation),R);}
 std::vector<Obs> query(const Path&p,const FrameStep&f,const Pack&pack,const std::vector<int>&history){std::vector<Obs>out;X center=add(f.C,mul(f.B[0],4)),wc=add(expand(center,invR),translation);double invnorm=0;for(X c:invR)invnorm+=dot(c,c);double radius=std::hypot(4.,.9),bound=radius*std::sqrt(invnorm)+1e-7;X bounds={bound,bound,bound};
 if(tight_roi){
   // Every surviving point satisfies this exact slab/template box. Transform its
   // eight-corner AABB analytically; retain a guard and the original exact filters.
   double mv=f.oa[0]+(pack.lo[0]+pack.hi[0])/2,mw=f.oa[1]+(pack.lo[1]+pack.hi[1])/2;
   X mid=add(f.C,expand({4,mv,mw},f.B));wc=add(expand(mid,invR),translation);
   X half={4,(pack.hi[0]-pack.lo[0])/2+.14,(pack.hi[1]-pack.lo[1])/2+.14};bounds={1e-7,1e-7,1e-7};
   for(int j=0;j<3;++j){X axis=expand(f.B[j],invR);for(int d=0;d<3;++d)bounds[d]+=std::abs(axis[d])*half[j];}
 }
 Cell lo=cell(sub(wc,bounds)),hi=cell(add(wc,bounds));for(int index:history){auto found=clouds.find(index);if(found==clouds.end())throw std::runtime_error("native history missing");auto&cloud=*found->second;std::vector<int>ids;auto query_begin=std::chrono::steady_clock::now();for(int x=lo.x;x<=hi.x;++x)for(int y=lo.y;y<=hi.y;++y)for(int z=lo.z;z<=hi.z;++z){auto it=cloud.cells.find({x,y,z});if(it!=cloud.cells.end())ids.insert(ids.end(),it->second.begin(),it->second.end());}std::sort(ids.begin(),ids.end());broad_points+=ids.size();if(profiling)profile["spatial_index_query"]+=std::chrono::duration<double>(std::chrono::steady_clock::now()-query_begin).count();Timer filtering_timer(profiling?&profile:nullptr,"ROI_transform_exact_filter");for(int i:ids){++transformed_points;X xyz=sensor(cloud.world[i]);if(norm(sub(xyz,center))>radius)continue;X q=local(sub(xyz,f.C),f.B);if(q[0]<0||q[0]>8||dot(sub(xyz,p.C),p.B[0])<=8+1e-8)continue;if(q[1]-f.oa[0]<pack.lo[0]-.14||q[1]-f.oa[0]>pack.hi[0]+.14||q[2]-f.oa[1]<pack.lo[1]-.14||q[2]-f.oa[1]>pack.hi[1]+.14)continue;out.push_back({(uint64_t(index)<<32)|uint32_t(i),xyz,q,current-index,0});}}roi_points+=out.size();if(trace_log.enabled){std::vector<uint64_t> ids;std::vector<double> xyz;for(auto&o:out){ids.push_back(o.key);for(double x:o.uvw)xyz.push_back(x);}event("ROI_exact",xyz,ids);}return out;}
 void candidates(FrameStep&f,const Pack&p,const Points&t,int step){for(size_t rank=0;rank<std::min(size_t(3),p.candidates.size());++rank){auto&c=p.candidates[rank];auto b=std::make_shared<Block>();b->a=c.a;b->C=f.C;b->B=f.B;b->step=step;b->rank=int(rank);std::set<X>unique;std::set<int>ages,bins;std::vector<double>inside,us;for(auto&o:f.roi){V q={o.uvw[1]-c.a[0],o.uvw[2]-c.a[1]};auto[d,bin]=nn(q,t);if(q[0]>=p.lo[0]&&q[0]<=p.hi[0]&&q[1]>=p.lo[1]&&q[1]<=p.hi[1]){inside.push_back(d);if(d<=.02){Obs accepted=o;accepted.residual=d;b->points.push_back(accepted);unique.insert(o.xyz);ages.insert(o.age);bins.insert(bin/4);us.push_back(o.uvw[0]);}}}int N=int(unique.size());std::sort(inside.begin(),inside.end());double shape=.5;if(!inside.empty()){int n=std::max(1,int(.7*inside.size()));shape=0;for(int i=0;i<n;++i)shape+=inside[i];shape/=n;}double margin=1;for(auto&other:p.candidates)if(std::sqrt(sq(other.a,c.a))>.04&&other.support>=3){margin=c.score-other.score;break;}auto second=overlap(f.old,t,c.a);double shift=std::sqrt(sq(c.a,f.oa));bool weak=N>=3&&shape<=.04&&shift<=.08*1.42&&margin>=.01&&(second.ok||second.weak||f.old.empty());if(!f.old.empty()&&(second.p90>.08||f.first>.08))weak=false;
 // Frozen C4 partial=subset intentionally enters tentative confirmation.
 if(trace_log.enabled){std::vector<uint64_t> ids;for(auto&o:b->points)ids.push_back(o.key);trace_log.add("support_acceptance",{double(step),double(rank),c.a[0],c.a[1],double(N),shape,margin,second.p90,f.first,shift,weak?1.:0.},ids,c.order);}if(!weak)continue;b->state=b->original=1;b->prior=std::exp(-shift/.08);b->score=(std::exp(-shape/.02)+b->prior+std::exp(-f.turn/3)+1+std::min(1.,ages.size()/3.)+std::min(1.,bins.size()/4.))/6-.3*std::max(0.,.05-margin)/.05;b->templ=c.score;b->confidence=std::max(0.,b->score)*(1-std::exp(-N/8.));b->anchor=add(f.C,expand({quantile(us,.5),c.a[0],c.a[1]},f.B));b->shape=shape;b->margin=margin;b->first=f.first;b->second=second.p90;f.accepted.push_back(b);}
 if(f.accepted.empty())f.reason=p.points.empty()?"NO_POINTS":p.candidates.empty()?"TOO_FEW_SUPPORT":"CANDIDATES_REJECTED";
 }
 Path run(Path initial,const Points&t,const std::vector<int>&history){std::vector<Path>active={initial},finished;for(int k=1;k<=40;++k){trace_log.step=k;trace_log.pack=-1;auto step_start=std::chrono::steady_clock::now();auto fit0=solver.fits,eval0=solver.evaluations,roi0=roi_points,broad0=broad_points,cp0=solver.candidate_points,fp0=solver.fit_points;ScopeExit step_timer{[&]{if(profiling)step_profile.push_back({double(k),double(roi_points-roi0),double(broad_points-broad0),double(solver.fits-fit0),double(solver.evaluations-eval0),std::chrono::duration<double>(std::chrono::steady_clock::now()-step_start).count(),double(solver.candidate_points-cp0),double(solver.fit_points-fp0)});}};++steps;std::vector<FrameStep>frames(active.size());std::vector<size_t>mapping;std::vector<Pack>packs;for(size_t i=0;i<active.size();++i){try{event("input_frame",{double(i),active[i].C[0],active[i].C[1],active[i].C[2],active[i].B[0][0],active[i].B[0][1],active[i].B[0][2],active[i].B[1][0],active[i].B[1][1],active[i].B[1][2],active[i].B[2][0],active[i].B[2][1],active[i].B[2][2]});frames[i]=next_frame(active[i]);mapping.push_back(i);packs.push_back(solver.prepare(frames[i].old,t,{0,0},.12,false,3));}catch(std::runtime_error&e){Path dead=active[i];dead.reason=e.what();finished.push_back(dead);frames[i].reason=e.what();}}solver.execute(packs,t);std::vector<size_t>nextmapping;std::vector<Pack>nextpacks;for(size_t n=0;n<mapping.size();++n){size_t i=mapping[n];auto&f=frames[i];auto&pack=packs[n];auto&p=active[i];X fallback;for(auto it=p.blocks.rbegin();it!=p.blocks.rend();++it)if((*it)->state==2){fallback=local(sub((*it)->anchor,f.C),f.B);break;}f.oa=pack.candidates.empty()?V{fallback[1],fallback[2]}:pack.candidates[0].a;auto check=overlap(f.old,t,f.oa);f.first=check.p90;f.firstok=check.ok;f.firstweak=check.weak;if(!pack.candidates.empty()&&!check.ok&&!check.weak){f.reason="OVERLAP_FIRST";continue;}f.roi=query(p,f,pack,history);Points points;for(auto&o:f.roi)points.push_back({o.uvw[1],o.uvw[2]});nextmapping.push_back(i);nextpacks.push_back(solver.prepare(std::move(points),t,f.oa,.08,false,3));}solver.execute(nextpacks,t);for(size_t n=0;n<nextmapping.size();++n)candidates(frames[nextmapping[n]],nextpacks[n],t,k);Timer beam_timer(profiling?&profile:nullptr,"beam_management_inclusive_promotion_copy");std::vector<Path>branches;
 for(size_t i=0;i<active.size();++i){auto&p=active[i];auto&f=frames[i];if(f.reason=="NO_CURRENT_GEOMETRY"||f.reason=="LOCAL_FRAME_DEGENERATE"||f.reason=="ORIENTATION_JUMP")continue;if(f.accepted.empty()){Path dead=p;dead.reason=f.reason;finished.push_back(dead);continue;}for(auto&b:f.accepted){Path child=p;child.C=f.C;child.B=f.B;child.blocks.clear();{Timer copy_timer(profile_context,"memory_allocation_copy");for(auto&old:p.blocks)child.blocks.push_back(std::make_shared<Block>(*old));}child.blocks.push_back(std::make_shared<Block>(*b));child.pending=0;for(auto&z:child.blocks)child.pending+=z->state==1;if(child.pending&&promote(child,*b)){for(auto&z:child.blocks)z->state=2;child.pending=0;}else if(b->state==2&&child.pending){child.blocks.back()->state=1;++child.pending;}if(child.pending>2){child.reason="TENTATIVE_UNCONFIRMED";finished.push_back(child);continue;}auto&last=*child.blocks.back();child.score+=last.score-(last.state==1?.4:0);double far=0;for(auto&o:last.points)far=std::max(far,norm(o.xyz));child.search=std::max(p.search,norm(add(f.C,mul(f.B[0],8))));if(far>=128){child.reason="RANGE_LIMIT";finished.push_back(child);}else branches.push_back(child);}}
 if(trace_log.enabled){std::vector<double> z;for(auto&b:branches){z.push_back(b.score);z.push_back(b.pending);z.push_back(b.blocks.back()->rank);}event("beam_before_ranking",z);}if(branches.empty()){active.clear();break;}std::stable_sort(branches.begin(),branches.end(),[](auto&a,auto&b){return a.score>b.score;});active.clear();for(auto&p:branches){if(std::any_of(active.begin(),active.end(),[&](const Path&o){return norm(sub(o.blocks.back()->anchor,p.blocks.back()->anchor))<.008;}))continue;active.push_back(p);if(active.size()==3)break;}}
 for(auto&p:active)finished.push_back(p);if(finished.empty())return initial;auto far=[](const Path&p){double d=0;for(auto&b:p.blocks)if(b->state==2)for(auto&o:b->points)d=std::max(d,norm(o.xyz));return d;};return *std::max_element(finished.begin(),finished.end(),[&](auto&a,auto&b){return a.score<b.score||(a.score==b.score&&far(a)<far(b));});
 }
 py::dict extend(Arr origin,Arr basis,py::array_t<int64_t> seed_ids,Arr templ,Arr pose,Arr inverse,int index,std::vector<int>history,double confidence){auto c=origin.unchecked<1>();auto b=basis.unchecked<2>();auto p=pose.unchecked<2>();auto inv=inverse.unchecked<2>();for(int j=0;j<3;++j){translation[j]=p(j,3);for(int i=0;i<3;++i){R[j][i]=p(i,j);invR[j][i]=inv(j,i);}}current=index;trace_log.events.clear();trace_log.step=0;trace_log.pack=-1;solver.next_pack=0;step_profile.clear();trace_context=trace_log.enabled?&trace_log:nullptr;profile_context=profiling?&profile:nullptr;ScopeExit reset_context{[]{trace_context=nullptr;profile_context=nullptr;}};for(int h:history)if(h>current||h<current-11||!clouds.count(h))throw std::runtime_error("invalid causal history");if(!clouds.count(index))throw std::runtime_error("missing current frame");Path path;path.C={c(0),c(1),c(2)};for(int j=0;j<3;++j)for(int i=0;i<3;++i)path.B[j][i]=b(i,j);auto seed=std::make_shared<Block>();seed->anchor=seed->C=path.C;seed->B=path.B;seed->confidence=confidence;auto ids=seed_ids.unchecked<1>();for(py::ssize_t i=0;i<ids.shape(0);++i){auto row=ids(i);if(row<0||size_t(row)>=clouds[index]->world.size())throw std::runtime_error("invalid seed row");X xyz=sensor(clouds[index]->world[row]);seed->points.push_back({(uint64_t(index)<<32)|uint32_t(row),xyz,local(sub(xyz,path.C),path.B),0,std::numeric_limits<double>::quiet_NaN()});path.search=std::max(path.search,norm(xyz));}if(seed->points.empty())throw std::runtime_error("empty seed");path.blocks={seed};Points t=read(templ);auto clock=std::chrono::steady_clock::now();{py::gil_scoped_release release;++updates;path=run(path,t,history);native_seconds+=std::chrono::duration<double>(std::chrono::steady_clock::now()-clock).count();}Timer output_timer(profiling?&profile:nullptr,"output_materialization");event("winner",{path.score,path.search,double(path.blocks.size()),double(path.pending)});py::dict out;py::list blocks;for(auto&z:path.blocks){py::dict d;std::vector<uint64_t>keys;std::vector<X>uvw;std::vector<double>res;for(auto&o:z->points){keys.push_back(o.key);uvw.push_back(o.uvw);res.push_back(o.residual);}d["keys"]=keys;d["uvw"]=uvw;d["residual"]=res;d["anchor_3d"]=z->anchor;d["anchor"]=z->a;d["basis_columns"]=z->B;d["plane_origin"]=z->C;d["step"]=z->step;d["state"]=z->state;d["original_state"]=z->original;d["confidence"]=z->confidence;d["continuity_score"]=z->score;d["template_score"]=z->templ;d["track_prior_score"]=z->prior;d["rank"]=z->rank;blocks.append(d);}out["blocks"]=blocks;out["reason"]=path.reason;if(trace_log.enabled)trace_log.add("stop:"+path.reason);out["path_score"]=path.score;out["search_range"]=path.search;return out;}
 py::dict stats(){auto d=solver.stats();d["profile"]=py::cast(profile);d["solver_profile"]=py::cast(solver.profile);d["step_profile"]=py::cast(step_profile);d["broad_points"]=broad_points;d["transformed_points"]=transformed_points;d["native_updates"]=updates;d["native_march_steps"]=steps;d["native_roi_points"]=roi_points;d["native_update_seconds"]=native_seconds;return d;}
};

