from . import ROOT,OUT
import long_common as lc
import numpy as np
import html,csv,datetime,json

def fmt(x,d=2):return '—' if x is None else f'{x:.{d}f}' if isinstance(x,(int,float)) else str(x)
def table(headers,rr):return '| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+'\n'.join('| '+' | '.join(fmt(v) for v in row)+' |' for row in rr)+'\n'
def main():
    m=lc.load(OUT/'METRICS.json');q=lc.load(OUT/'FINAL_LINUX_QUALITY.json');lock=lc.load(OUT/'REALTIME_SELECTION_LOCK.json');dev=lc.load(OUT/'development.json');control=m['plus100k'];w=lock['workers'];t=lock['threads']
    selected=[r for r in m['workers'] if r['workers']==w and r['threads']==t and r['file'].startswith('confirmation')]
    lookup={(r['mode'],r['metric']):r for r in m['timing']};mem=lookup['Linux_bind','wall_ms'];c4=lookup['Linux_bind','c4_ms'];offline=lookup['Linux_bind','offline_full_ms'];ext=lookup['Linux_ext4','offline_full_ms'];system=all(r['system_pass'] for r in selected) and len(selected)==2
    decision='A' if mem['median']<=100 else 'B' if mem['median']<=200 else 'C' if system else 'D';production=q['quality_pass'] and (decision in ('A','B') or system)
    summary=dict(decision=decision,production_default=production,linux_quality_pass=q['quality_pass'],workers=w,threads=t,system_gate=system,single_memory_median_ms=mem['median'],single_memory_p95_ms=mem['p95'],live_c4_median_ms=c4['median'],live_c4_p95_ms=c4['p95'],offline_bind_median_ms=offline['median'],offline_ext4_median_ms=ext['median'],selected_live=selected)
    lc.save(OUT/'FINAL_DECISION.json',summary)
    chunks=[];add=chunks.append
    add('# FINAL REALTIME — Linux, точный ROI, общая история и независимые solve\n\n'+datetime.datetime.now().strftime('%Y-%m-%d')+' · Ryzen 9 7950X3D, 16 физических / 32 логических CPU · Docker Linux, 32 доступных vCPU.\n')
    add(f'**Решение {decision}. Linux quality: {"PASS" if q["quality_pass"] else "FAIL"}. Native production default: {"ДА, для описанного Linux режима" if production else "НЕТ"}.** Выбран {w} solve worker × {t} candidate threads. Каждый C4 строится заново; между кадрами разрешено использовать только уже готовую итоговую геометрию.\n')
    add('## Главные числа\n\n'+table(['Режим, фиксированные 48 стартов','Median, мс','p95, мс'],[['LIVE_MEMORY C4, включая Python materialization',c4['median'],c4['p95']],['LIVE_MEMORY RAW → конечные рельсы',mem['median'],mem['p95']],['OFFLINE_LAS Windows bind: чтение + индексы + solve',offline['median'],offline['p95']],['OFFLINE_LAS Linux volume/ext4: чтение + индексы + solve',ext['median'],ext['p95']]]))
    add('RAM-цифры начинаются после готовности FrameData, source metadata и индекса. OFFLINE включает их подготовку. В live-тесте эта работа не спрятана: подготовка каждого прибывающего кадра включена в задержку raw consumer. Ожидание разрешённой pose T+1 — ещё один период входа (~100 мс); оно не входит в compute latency. Сериализация исследовательских NPZ и LAS export не входят в solve.\n')
    add(table(['Дальность','Reference far p95, см','Native far p95, см','Δ, см','Сечений / стартов','Gate'],[[f'{r["lo"]}–{r["hi"]} м',100*r['reference_p95'],100*r['native_p95'],100*r['p95_delta_m'],f'{r["stations"]} / {r["starts"]}',r['gate']] for r in q['ranges'] if r['component']=='far']))
    add(table(['Live 10 Hz, по 200 кадров','Publish Hz','Solve Hz','CPU cores','Raw p95, мс','Deadline p95, мс','Положительный горизонт','Gate'],[[r['run'],r['publish_hz'],r['solve_hz'],r['active_cores'],r['raw_consumer_p95_ms'],r['raw_deadline_p95_ms'],f'{100*r["positive_horizon_fraction"]:.1f}%',r['system_pass']] for r in selected]))
    add('Вход 10 Гц не означает 10 новых геометрий в секунду. Частота публикаций указана отдельно; между публикациями готовая геометрия переводится в текущую систему координат. Поток не накапливает старые задания: максимум N активных solve и один заменяемый pending. Отрицательный или отсутствующий горизонт не объявляется положительным.\n')
    add(table(['Размер работы на 48 стартах','Median','p95'],[[key,m['point_summary'][key]['median'],m['point_summary'][key]['p95']] for key in ('raw_points','history_points','broad_points','roi_points','candidate_points','fit_points','selected_points')]))
    add('`broad_points`, `roi_points`, `candidate_points`, `fit_points` — суммы по запросам/пакетам одного solve, не число уникальных точек во всём облаке. Одни строки могут проверяться в нескольких гипотезах. `selected_points` — уникальные строки provenance всего pipeline, включая STEP1/STEP2. Подробные значения по шагам: [per_step_points.csv](per_step_points.csv).\n')
    add('## Что проверено и когда\n\nПервым выполнен неизменённый Linux reference против неизменённого Linux native: 240 held-out стартов × 2 backend. Строгий gate +1 см прошёл ещё до оптимизаций. Затем варианты выбирались только на development: 32 paired ablation-старта и все 200 development-стартов для точного сравнения. Все 200 сохранили C4 IDs, anchors, local coordinates, states, residuals и итоговые C/B/pair/s/q. После выбора и записи [REALTIME_SELECTION_LOCK.json](REALTIME_SELECTION_LOCK.json) candidate один раз пересчитан на 240 held-out стартах.\n\nLinux reference final использует сохранённые результаты первого полного запуска: frozen Python/C++ reference и parent Linux image неизменны. Это явно отмечено в inference manifest; новый candidate рассчитан заново. GT-кэши читаются только после завершения inference. Проверка final против прежнего Linux native: [final_vs_linux_baseline.csv](final_vs_linux_baseline.csv).\n')
    add('## Почему расходились Windows и Linux\n\nНа десяти **битово одинаковых** сохранённых входах Windows/MSVC и Linux/GCC выбрали одинаковые IDs и битово одинаковые anchors. Первое различие диагностических costs — 1–2 ULP, без изменения выбранной геометрии. Linux GCC против Clang и один поток против восьми дали целиком одинаковые сохранённые traces на этих десяти входах. Это не доказательство всех возможных сцен, но прямой контроль подозреваемых compiler/thread факторов.\n\nПри сравнении реальных полных pipeline различаются лишь C4 input `origin` и `confidence`; raw XYZ, basis, pose, inverse, template, seed IDs и history совпадают. Контрфактическая подстановка только Linux `origin` в тот же Windows solver воспроизводит расхождение. Подстановка только confidence геометрию не меняет. Следовательно, источник — upstream STEP2/bootstrap anchor и чувствительность последующих численных ветвлений, а не случайная очередность потоков C4. Точный внутренний первоисточник округления внутри upstream SciPy/NumPy по этим C4 traces не установлен; приписывать его конкретной libm-инструккции было бы необоснованно.\n\nПример `doubleT_platform / 44`: первый дискретный split на step 13, pack 64, candidate 4, LM iteration 10, trial 0 — сравнение нового cost с прежним принимает шаг с одним bootstrap origin и отклоняет с другим. На `88` это step 10, pack 44, candidate 1, iteration 11. Малое изменение входа уже накопилось к этим проверкам; это не означает сантиметровой ошибки исходной точки. Linux признан канонической платформой, искусственное округление bootstrap и изменения frozen STEP2 не внесены.\n\nФайлы: [first numeric divergence](cross_os_first_divergence.csv), [first branch](cross_os_first_branch.csv), [input deltas](cross_os_input_difference.csv), [counterfactual swaps](cross_os_input_counterfactual.csv), [traces](determinism_trace/).\n')
    add('### Аудит порядка и floating point\n\nSpatial hash используется для поиска по явно перечисленным cell coordinates; найденные point IDs сортируются до фильтров. Нет обхода unordered-map как порядка суммирования и нет pointer ordering. Candidate jobs записываются в заранее определённые slots. Векторы residuals и normal equations суммируются последовательно в double, межпоточных reductions нет. Stable ranking сохраняет фиксированный ordinal seed/branch при одинаковом score — детерминированный tie-break. NN полный точный перебор; approximate NN отсутствует. NaN seed residual — предусмотренное поле без измеренного residual, не значение score. Нефинитные входные 2D координаты отклоняются. Проверки compiler: portable GCC 12.2 / Clang, C++17, `-O3 -fno-fast-math -ffp-contract=off -fno-associative-math`. Pybind11 включает LTO по умолчанию; отдельный эффект LTO не измерялся.\n')
    add('## Что изменено в runtime\n\n`SharedRing` принимает immutable FrameData, один раз считает source XYZ/distance/azimuth и строит native spatial grid в map coordinates. Snapshot владеет ссылками только на разрешённые T−11…T кадры с остановкой на time/pose gap. Native Marcher получает shared_ptr на те же облака и индексы. При вытеснении из ring активный snapshot сохраняет lifetime объектов. Полная история не копируется на каждого работника. В кеше нет fitted C4 curve.\n\nПри query сначала строится консервативный map-space AABB точного текущего 0–8 м slab/template ROI. Из индекса выбирается superset, затем выполняются прежние sphere/slab/new-point/template проверки в прежнем порядке. Ни одна ROI-ширина, LM-итерация, beam size или support threshold не менялась. Это локальный ROI каждого шага/гипотезы, а не глобальное предположение о прямом тоннеле.\n\nВ Python исторические XYZ преобразуются в систему T только для выбранных строк; metadata индексируется по source row. Полное историческое облако больше не трансформируется ради нескольких сотен возвращённых точек. Повторный `np.isin` по полному текущему облаку заменён точным поиском ключей в уже отсортированном массиве. Текущий полный raw frame остаётся входом STEP1/STEP2. Все measurement fields и point provenance сохранены.\n')
    add('### Ablation на фиксированных 32 development-стартах\n\n'+table(['Вариант','Median полного solve','p95','Ускорение','Решение'],[[r['variant'],r.get('median'),r.get('p95'),r.get('speedup'),r['decision']] for r in m['ablations']]))
    add('`memory_broad` объединяет RAM ring и построение индекса на arrival: их отдельный speedup не выдаётся за измеренный. `memory_selective` добавляет выборочное materialization; `memory_exact` — точный AABB. Последующая замена типа ключа выключенного Timer убирает служебное выделение строк, не меняя вычисления; дополнительно прошли 32 exact profile-сравнения. Не делались combined global index, thinning, PGO, CPU-specific ISA/FMA: сработало правило STOP. Эти варианты отмечены NOT_RUN, а не PASS.\n')
    add('## Point count и стоимость +100 тысяч точек\n\n'+table(['Контроль +100k raw rows, 8 development cases × 3 пары','Медианная добавка, мс','p95 добавки, мс'],[[k,v['median'],v['p95']] for k,v in control.items()]))
    add('В контроле добавлены 100 000 raw точек позади сенсора, гарантированно вне исследуемого переднего коридора; исходные строки сохранены. C4 IDs и финальная геометрия каждой пары совпали точно. Это измеряет стоимость лишнего raw объёма при неизменном полезном ROI. Это **не** стоимость 100k дополнительных опорных точек внутри ROI: такая интервенция изменила бы задачу и геометрию. Добавка в solve обусловлена прежде всего полными current-frame операциями STEP1/STEP2, metadata и provenance/materialization. Исторические далёкие точки после построения spatial index больше не требуют сканирования каждого шага.\n\n[Regression CSV](runtime_regression.csv) содержит Pearson, Spearman, простой slope и exploratory multivariable OLS для raw/history/ROI/candidate counts, числа fits и шагов. Коррелированные кадры, различный горизонт и геометрия сцены не позволяют трактовать observational slope как физическую константу ms/100k. Приведены rank/condition number и ошибки коэффициентов. Прямой контроль выше — более узкий, но причинно понятный ответ.\n')
    add('## Где время и почему не используются 16 ядер\n\nПрежний профиль посещал миллионы broad-phase points за solve ради порядка десяти тысяч exact-ROI rows. В wall time были последовательные чтение LAS, history materialization, преобразования всех исторических XYZ и управление шагами/beam. Candidate fitting параллелен только внутри небольших пакетов; шаги марчинга зависимы друг от друга. STEP1/STEP2, contract, smoothing, STEP6 и Python orchestration сохраняют последовательные участки.\n\nТаймеры: [roi_timing.csv](roi_timing.csv), [history_index_timing.csv](history_index_timing.csv). `candidate_batch_wall` — wall; `LM_fitting`, `NN`, `residual_evaluation` по candidate threads суммированы и вложены друг в друга. Их нельзя складывать как независимые wall-компоненты. Профилированные запуски не используются как чистые latency-замеры. Allocation/copy, tentative confirmation, PCA и output materialization выделены отдельно.\n\nНезависимые Python threads с native GIL release действительно увеличили process CPU примерно до 2–2.5 ядра, но 4–8 workers дали конкуренцию в оставшихся Python участках и ухудшили свежесть. Наблюдения согласуются с ограничением GIL/последовательных stages; прямой процент времени ожидания GIL отдельно не инструментировался. Полного масштабирования на 16 физических ядер эта работа не продемонстрировала. Это отражено в выборе режима, а не скрыто за 10 Hz input.\n')
    add(table(['Workers × threads, 100 кадров','Publish Hz','Solve Hz','Median solve, мс','CPU cores','Positive horizon','Gate'],[[f'{r["workers"]}×{r["threads"]}',r['publish_hz'],r['solve_hz'],r['solve_p50_ms'],r['active_cores'],f'{100*r["positive_horizon_fraction"]:.1f}%',r['system_pass']] for r in m['workers'] if r['file'].startswith('development')]))
    add('### Scheduler, causality и память\n\nНовейший eligible pending заменяет старый. Job получает causal snapshot до вытеснения старого кадра при arrival T+1; future cloud не передаётся. Из будущего разрешена только поза T+1. Результат публикуется только если его source frame строго новее последнего опубликованного и совпадает generation. Старый completion и результат через gap отбрасываются. Неудачный solve не стирает существующую допустимую геометрию; gap её сбрасывает. Unit checks проверяют удержание старого snapshot после eviction без копирования, запрет future/expired source и запрет stale/gap publication.\n\n[worker_matrix.csv](worker_matrix.csv), [realtime_10hz.csv](realtime_10hz.csv), [publish_latency.csv](publish_latency.csv), [cpu_utilization.csv](cpu_utilization.csv), [memory.csv](memory.csv). В RSS входит заранее прочитанный producer-only replay fixture из 100/200 кадров; worker не имеет к нему доступа. Поэтому этот RSS нельзя называть обязательной production-памятью истории. Python ring bytes и native XYZ bytes приведены отдельно; spatial grid и удерживаемые активными snapshots старые кадры добавляют память. Суммировать per-job process CPU нельзя: при параллельности интервалы пересекаются. Для подтверждающих прогонов отдельно измерено CPU собственного worker thread, без candidate pool threads.\n')
    add('## Итоговое качество Linux\n\n'+table(['Компонент','Диапазон, м','Reference p95, см','Native p95, см','Δ, см','N сечений / стартов'],[[r['component'],f'{r["lo"]}–{r["hi"]}',100*r['reference_p95'],100*r['native_p95'],100*r['p95_delta_m'],f'{r["stations"]} / {r["starts"]}'] for r in q['ranges']]))
    add(table(['Катастрофический критерий','Reference starts','Native starts','Новых','Убрано'],[[f'{r["scope"]} > {r["threshold_m"]*100:.0f} см',r['reference'],r['native'],r['new'],r['removed']] for r in q['catastrophic'] if r['threshold_m'] in (.2,.5)]))
    add(table(['Backend','Availability','Горизонт median, м','p95, м','≥30 м','≥50 м','≥75 м'],[[a['backend'],f'{a["available"]}/{a["total"]}',h['median'],h['p95'],f'{h["p_ge_30"]*100:.1f}%',f'{h["p_ge_50"]*100:.1f}%',f'{h["p_ge_75"]*100:.1f}%'] for a,h in zip(q['availability'],q['horizon'])]))
    add(table(['Gate','Значение','Предел','Результат'],[[g['gate'],g.get('value'),g.get('limit'),g['status']] for g in q['gates']]))
    add('На 75–100 м только 83 общих сечения / 12 стартов: прежний минимум достаточности выполнен, но это небольшая коррелированная выборка. GT получен из человеческой разметки и оценённых registration poses, а не геодезической съёмки. Поэтому сантиметровое расхождение с GT не всегда ошибка detector. Практический допуск ~2 см для far-bin не понадобился: строгий +1 см прошёл. Новые структурные ошибки, wrong-side/crossing/swap проверены отдельно.\n\n[Полная галерея: лучшие, средние, худшие и прямые/кривые примеры](linux_final/gallery.html) · [Worst cases](linux_final/worst_regressions.csv) · [Per-start quality](linux_final/benchmark_per_start.csv).\n')
    worst=sorted([c for c in q['cases'] if 'far_p95_delta' in c],key=lambda c:-c['far_p95_delta'])[:8]
    add('### Самые большие локальные регрессии\n\n'+table(['Запись / кадр','Far p95 reference → native, см','Δ, см','Изменение CR p95, см','Источник расхождения','Горизонт ref → native, м'],[[f'{c["run"]} / {c["frame"]:06d}',f'{c["reference_far_p95"]*100:.2f} → {c["native_far_p95"]*100:.2f}',c['far_p95_delta']*100,c['cr_disagreement_p95']*100,c['dominant_difference'],f'{c["reference_horizon"]:.1f} → {c["native_horizon"]:.1f}'] for c in worst]))
    add('Эти локальные различия — native против reference, существовавшие до точных ROI-оптимизаций. Полный final-vs-baseline CSV проверяет это напрямую. Поле «источник» — геометрическая декомпозиция изменения CR и положения ходового рельса относительно CR, не доказательство дефекта GT или конкретного sensor-return. Расширение native coverage отдельно оценено и не заменяет сравнение на общих сечениях.\n')
    add('## Эксплуатация и ограничения\n\nКод изолирован в `MVP/realtime_final/`, старые stages и исходные LAS не изменены. Docker: `deptrans-realtime:production`. Рекомендуемый runtime API — `Scheduler.arrival(FrameData)` с pose metadata и постоянным raw ring. `Scheduler.poll()` вызывается и между поступлениями, чтобы своевременно публиковать completion. Для offline запуска есть `python -B -m MVP.realtime_final.cli RUN --output DERIVED --start 0 --count 100`; `--threads` задаёт candidate pool, `--mode live-replay --workers N` запускает измеряемое воспроизведение. Параметры production зафиксированы в lock/README.\n\nАртефакты timing рассчитаны без одновременного второго benchmark. Bind и volume — warm OS-cache replay, не обещание cold-disk времени. 20-секундные moving runs проверяют данный режим, но не заменяют многочасовой soak test. Frozen STEP1/STEP2/C4_SMOOTH/STEP6 и seed adapter остаются прежними. Работа не включает obstacle detection, ROS installation, новые геометрические модели или persistence траектории.\n\n[Рекомендация](FINAL_REALTIME_RECOMMENDATION.md) · [Manifest](FINAL_MANIFEST.json) · [Проверки](VERIFICATION.json).\n')
    text='\n'.join(chunks);(OUT/'REPORT_REALTIME_FINAL.md').write_text(text,encoding='utf-8')
    # Small offline Markdown renderer for paragraphs, headings, tables and links.
    import re
    def inline(x):
        x=html.escape(x);x=re.sub(r'\*\*(.+?)\*\*',r'<strong>\1</strong>',x);x=re.sub(r'`([^`]+)`',r'<code>\1</code>',x);return re.sub(r'\[([^]]+)\]\(([^)]+)\)',r'<a href="\2">\1</a>',x)
    body=[];lines=text.splitlines();i=0
    while i<len(lines):
        line=lines[i]
        if line.startswith('|'):
            group=[]
            while i<len(lines) and lines[i].startswith('|'):group.append(lines[i]);i+=1
            body.append('<div class="scroll"><table>')
            for j,row in enumerate(group):
                if j==1:continue
                tag='th' if j==0 else 'td';body.append('<tr>'+''.join(f'<{tag}>{inline(c.strip())}</{tag}>' for c in row.strip('|').split('|'))+'</tr>')
            body.append('</table></div>');continue
        if line.startswith('#'):
            n=len(line)-len(line.lstrip('#'));body.append(f'<h{n}>{inline(line[n:].strip())}</h{n}>')
        elif line.strip():body.append('<p>'+inline(line)+'</p>')
        i+=1
    page='<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Final Realtime Qualification</title><style>body{font:16px/1.55 system-ui;color:#233348;background:#f0f4f9;max-width:1500px;margin:auto;padding:32px}h1{font-size:34px}h2{margin-top:45px}table{border-collapse:collapse;width:100%;background:white}th,td{padding:10px 12px;border-bottom:1px solid #dbe3ed;text-align:left}th{background:#183b60;color:white}.scroll{overflow:auto;margin:20px 0}a{color:#0763a1}code{background:#e4ebf4;padding:2px 5px}p{max-width:1250px}strong{color:#164c36}</style>'+''.join(body)+'</html>'
    (OUT/'REPORT_REALTIME_FINAL.html').write_text(page,encoding='utf-8')
    rec=f'# Production recommendation — {decision}\n\nLinux quality: {q["quality_pass"]}. Production native default: {production}.\n\nUse {w} solve worker × {t} candidate threads, fresh full native, exact ROI, no thinning, no C4 persistence.\n\nUnloaded LIVE_MEMORY full pipeline median / p95: {mem["median"]:.1f} / {mem["p95"]:.1f} ms. C4: {c4["median"]:.1f} / {c4["p95"]:.1f} ms.\n\n'+table(['Run','Publish Hz','CPU cores','Positive horizon','Raw p95 ms'],[[r['run'],r['publish_hz'],r['active_cores'],100*r['positive_horizon_fraction'],r['raw_consumer_p95_ms']] for r in selected])+'\n10 Hz describes input/consumer service; geometry is refreshed at the measured publish rate. Keep the newest pending request only and reject late older results. Do not select 4–8 workers: measured horizon deteriorates.\n\nCross-OS difference: upstream bootstrap origin perturbation, amplified by LM/branch sensitivity. Canonical Linux passes the strict original quality gates. No claim of universal Windows/Linux bitwise equivalence.\n\nSTOP rule applied: no PGO, density thinning or CPU-specific tuning. Full methodology and caveats: [report](REPORT_REALTIME_FINAL.html).\n'
    (OUT/'FINAL_REALTIME_RECOMMENDATION.md').write_text(rec,encoding='utf-8');print('REPORT_COMPLETE',summary)
if __name__=='__main__':main()
